title: Raul Anselmo dos Santos Farias - Portfólio
description: "Portfólio de Raul Anselmo dos Santos Farias, desenvolvedor e especialista em tecnologia."
author: Raul Anselmo dos Santos Farias
email: raul.trabalho5511@gmail.com
social:
  github: https://github.com/RaulAnselmoDSantos/RaulAnselmoPortfolio.git
  linkedin: https://www.linkedin.com/in/raul-anselmo/
theme: jekyll-theme-minimal
